# Generated by Django 3.2.4 on 2021-06-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210621_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='document',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
