runtime: python
env: flex
entrypoint: bash -c 'python manage.py migrate --noinput && gunicorn -b :$PORT settings.wsgi'
threadsafe: true
runtime_config:
  python_version: 3
env_variables:
  DB_HOST: '35.239.249.79'
  DB_PORT: '3306'
  DB_NAME: 'accountapi'
  DB_USER: 'account'
  DB_PASSWORD: 'KPgh4cBmhExy9yoO'
handlers:
- url: /.*
  script: auto
  secure: always