runtime: python
env: flex
entrypoint: bash -c 'python manage.py migrate --noinput && gunicorn -b :$PORT settings.wsgi'
threadsafe: true
runtime_config:
  python_version: 3
env_variables:
  DB_HOST: '/cloudsql/essential-rider-317517:us-central1:accountdbapi2'
  DB_PORT: '3306'
  DB_NAME: 'accountapi'
  DB_USER: 'account'
  DB_PASSWORD: 'KPgh4cBmhExy9yoO'
handlers:
- url: /.*
  script: auto
  secure: always
beta_settings:
    cloud_sql_instances: essential-rider-317517:us-central1:accountdbapi2